# define a dictionary of configuration parameters and their values
root_dir: "/home/kuan-hao/Documents/bioinformatics/Virus"
ref: "virus_data"
wordir: "VirusRNASeq"
tool_dir: "/home/kuan-hao/Documents/tools"
