# Generated by Django 2.1.5 on 2019-01-24 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_hash', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('data_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='NewsletterUsers',
        ),
    ]
