# Generated by Django 2.1.5 on 2019-01-29 15:51

from django.db import migrations, models
import email_hash.models


class Migration(migrations.Migration):

    dependencies = [
        ('email_hash', '0003_newsletteruser_analysis_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletteruser',
            name='analysis_code',
            field=models.CharField(default=email_hash.models.analysis_code_generator, max_length=32),
        ),
    ]
