datadir: /Users/chaokuan-hao/Documents/bioinformatics/Virus/VirusRNASeq/VirusRNASeq/media/tmp/Project834a848828fd11e99ae360f81dacbf14_ck1021051@gmail.com_8798863428fd11e99ae360f81dacbf14
fastqc:
  fastqc_command: /Users/chaokuan-hao/Documents/bioinformatics/Virus/tools/FastQC/fastqc
project_name: Project834a848828fd11e99ae360f81dacbf14
se_or_pe: pe
trimmomatic:
  adapter: /Users/chaokuan-hao/Documents/bioinformatics/Virus/tools/Trimmomatic/adapters/TruSeq3-PE.fa
  adapter_param: :2:30:10
  leading: '8'
  minlen: '36'
  phred: -phred33
  threads: 8
  trailing: '8'
  trimmomatic_jar: /Users/chaokuan-hao/Documents/bioinformatics/Virus/tools/Trimmomatic/trimmomatic-0.38.jar
  window_quality: '20'
  window_size: '4'
