# Generated by Django 2.1.5 on 2019-01-29 19:44

from django.db import migrations, models
import email_hash.models


class Migration(migrations.Migration):

    dependencies = [
        ('email_hash', '0004_auto_20190129_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletteruser',
            name='project_name',
            field=models.CharField(default=email_hash.models.project_name_generator, max_length=100),
        ),
    ]
