# Generated by Django 2.1.5 on 2019-02-03 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_hash', '0005_newsletteruser_project_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletteruser',
            name='analysis_code',
            field=models.CharField(max_length=32),
        ),
    ]
