# Generated by Django 2.1.7 on 2019-03-18 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_hash', '0006_auto_20190203_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletteruser',
            name='assembly_type_input',
            field=models.CharField(default='de_novo_assembly', max_length=32),
        ),
    ]
