# Generated by Django 2.1.5 on 2019-02-04 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190204_1745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_normal_user',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_tmp_user',
        ),
    ]
