# Generated by Django 2.1.5 on 2019-02-04 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190204_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_normal_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_tmp_user',
            field=models.BooleanField(default=True),
        ),
    ]
