datadir: /Users/chaokuan-hao/Documents/bioinformatics/Virus/VirusRNASeq/VirusRNASeq/media/tmp/Projectf172f806337411e9842f60f81dacbf14_ck1021051@gmail.com_043fce1e337511e9939660f81dacbf14
project_name: Projectf172f806337411e9842f60f81dacbf14
se_or_pe: pe
trimmomatic:
  adapter: /Users/chaokuan-hao/Documents/bioinformatics/Virus/tools/Trimmomatic/adapters/TruSeq3-PE.fa
  adapter_param: :2:30:10
  leading: '8'
  minlen: '36'
  phred: -phred33
  threads: 8
  trailing: '8'
  trimmomatic_jar: /Users/chaokuan-hao/Documents/bioinformatics/Virus/tools/Trimmomatic/trimmomatic-0.38.jar
  window_quality: '20'
  window_size: '4'
