from snakemake.utils import min_version
import os
from snakemake.shell import shell
import pandas as pd

__author__ = 'Kuan-Hao Chao <b05901180@ntu.edu.tw>'

#------------ Config setup ------------
configfile: "config.yaml"
print(os.path.join(config["datadir"], config["se_or_pe"]))
workdir: os.path.join(config["datadir"])
trimmomatic_jar = config["trimmomatic"]["trimmomatic_jar"]
# pipesDir = os.path.join(os.path.expanduser(config['bin_dir']), 'pipes', 'rules')

# Tabular configuration
# samples = pd.read_table(config["samples"]).set_index("sample", drop=FALSE)
# validate(samples, schema="schemas/cells.schema.yaml")

#------------ Definition fo all_input ------
samples = {os.path.splitext(os.path.splitext(os.path.splitext(f)[0])[0])[0] for f in os.listdir(os.path.join(config["datadir"], config["se_or_pe"])) if f.endswith(".fastq.gz")}
print(samples)

#------------ Target File -------------

rule targets:
    input:
        expand(os.path.join("fastqc", "pre", "{sample}.R1_fastqc.html"), sample=samples),
        expand(os.path.join("trimmed_paired", "{sample}_r1_paired.fastq.gz"), sample=samples),
        expand(os.path.join("fastqc", "post", "{sample}_r1_paired_fastqc.html"), sample=samples),

rule first_fastqc:
    input:
        r1 = os.path.join(config["se_or_pe"], "{sample}.R1.fastq.gz"),
        r2 = os.path.join(config["se_or_pe"], "{sample}.R2.fastq.gz"),
    output:
        html_r1 = os.path.join("fastqc", "pre", "{sample}.R1_fastqc.html"),
        zip_r1 = os.path.join("fastqc", "pre", "{sample}.R1_fastqc.zip"),
        html_r2 = os.path.join("fastqc", "pre", "{sample}.R2_fastqc.html"),
        zip_r2 = os.path.join("fastqc", "pre", "{sample}.R2_fastqc.zip"),
    shell:
        """
        {config[fastqc][fastqc_command]} {input.r1} {input.r2} --outdir=fastqc/pre
        """

rule trimmomatic_pe:
    input:
        r1 = os.path.join(config["se_or_pe"], "{sample}.R1.fastq.gz"),
        r2 = os.path.join(config["se_or_pe"], "{sample}.R2.fastq.gz"),
    output:
        r1_paired = os.path.join("trimmed_paired", "{sample}_r1_paired.fastq.gz"),
        r1_unpaired = os.path.join("trimmed_unpaired", "{sample}_r1_unpaired.fastq.gz"),
        r2_paired = os.path.join("trimmed_paired", "{sample}_r2_paired.fastq.gz"),
        r2_unpaired = os.path.join("trimmed_unpaired", "{sample}_r2_unpaired.fastq.gz"),
    log:
        log = os.path.join("log", "{sample}.log")
    message: "Trimming Illumina adapters from {input.r1} and {input.r2}"
    params:
        # list of trimmers (see manual)
        trimmer=["CROP:151"],
        minilength=["MINLEN:50"],
        # optional parameters
        extra="-phred33",
    shell:
        """
        java -jar {config[trimmomatic][trimmomatic_jar]} PE -threads {config[trimmomatic][threads]} {config[trimmomatic][phred]} {input.r1} {input.r2} {output.r1_paired} \
        {output.r1_unpaired} {output.r2_paired} {output.r2_unpaired} \
        ILLUMINACLIP:{config[trimmomatic][adapter]}{config[trimmomatic][adapter_param]} LEADING:{config[trimmomatic][leading]} TRAILING:{config[trimmomatic][trailing]} SLIDINGWINDOW:{config[trimmomatic][window_size]}:{config[trimmomatic][window_quality]} MINLEN:{config[trimmomatic][minlen]}
        """


rule second_fastqc:
    input:
        r1_paired = os.path.join("trimmed_paired", "{sample}_r1_paired.fastq.gz"),
        r1_unpaired = os.path.join("trimmed_unpaired", "{sample}_r1_unpaired.fastq.gz"),
        r2_paired = os.path.join("trimmed_paired", "{sample}_r2_paired.fastq.gz"),
        r2_unpaired = os.path.join("trimmed_unpaired", "{sample}_r2_unpaired.fastq.gz"),
    output:
        html_r1_paired = os.path.join("fastqc", "post", "{sample}_r1_paired_fastqc.html"),
        zip_r1_paired = os.path.join("fastqc", "post", "{sample}_r1_paired_fastqc.zip"),
        html_r1_unpaired = os.path.join("fastqc", "post", "{sample}_r1_unpaired_fastqc.html"),
        zip_r1_unpaired = os.path.join("fastqc", "post", "{sample}_r1_unpaired_fastqc.zip"),
        html_r2_paired = os.path.join("fastqc", "post", "{sample}_r2_paired_fastqc.html"),
        zip_r2_paired = os.path.join("fastqc", "post", "{sample}_r2_paired_fastqc.zip"),
        html_r2_unpaired = os.path.join("fastqc", "post", "{sample}_r2_unpaired_fastqc.html"),
        zip_r2_unpaired = os.path.join("fastqc", "post", "{sample}_r2_unpaired_fastqc.zip"),
    shell:
        """
        {config[fastqc][fastqc_command]} {input.r1_paired} {input.r1_unpaired} {input.r2_paired} {input.r2_unpaired} --outdir=fastqc/post
        """


#------------ include rules -----------
# include: "./rules/trimmomatic_trimming_PE.snakefile"
# include: "./rules/bwa_alignment.snakefile"


#------------ setup report ------------
