# Generated by Django 2.1.7 on 2019-03-06 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataanalysis', '0003_pairedend_photo_singleend'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Photo',
            new_name='Data',
        ),
    ]
