# Generated by Django 2.1.7 on 2019-03-11 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataanalysis', '0004_auto_20190306_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='analysis_code',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='data',
            name='email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='data',
            name='project_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
