# Generated by Django 2.1.7 on 2019-03-18 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataanalysis', '0005_auto_20190312_0754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='analysis_code',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='data',
            name='email',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='data',
            name='project_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='data',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
